# Generated by Django 4.2.13 on 2024-06-19 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Students', '0003_deletedstudentforclasses_deletedstudent'),
        ('Workers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='StudentMonthPayments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_price', models.IntegerField()),
                ('payed', models.IntegerField()),
                ('another', models.IntegerField()),
                ('month', models.DateTimeField()),
                ('real_price', models.IntegerField()),
                ('discount_percentage', models.IntegerField()),
                ('account_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Workers.accounttype')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Students.students')),
            ],
        ),
        migrations.CreateModel(
            name='StudentPaymentsInMonth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payed', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('account_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Workers.accounttype')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Students.students')),
                ('student_month_payments', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_payments_in_month', to='account.studentmonthpayments')),
            ],
        ),
        migrations.CreateModel(
            name='StudentDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_percentage', models.IntegerField()),
                ('discount_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.discounttype')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_discount', to='Students.students')),
            ],
        ),
        migrations.CreateModel(
            name='Overhead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('payed', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('account_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Workers.accounttype')),
            ],
        ),
        migrations.CreateModel(
            name='DeleteDOverhead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('over_head', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.overhead')),
            ],
        ),
    ]
