# Generated by Django 4.2.13 on 2024-06-19 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Teachers', '0003_alter_teacher_salary_type_alter_teacher_subject_id_and_more'),
        ('Calendar', '0001_initial'),
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonPlanDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('target', models.TextField()),
                ('main', models.TextField()),
                ('assessment', models.TextField()),
                ('homework', models.TextField()),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Calendar.day')),
                ('lesson_time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.timelist')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Teachers.teacher')),
            ],
        ),
    ]
