# Generated by Django 4.2.13 on 2024-06-19 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Teachers', '0002_teachersalarytype_remove_teacher_subject_and_more'),
        ('Class', '0002_deletedclasses'),
        ('Flow', '0002_languagetype'),
        ('Subjects', '0001_initial'),
        ('Rooms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_count', models.CharField(max_length=255)),
                ('start', models.CharField(max_length=255)),
                ('end', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TimeTableDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DailyTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flow_lesson', models.BooleanField(default=False)),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_tables', to='Class.class')),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_tables', to='timetable.timetableday')),
                ('flow', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='daily_tables', to='Flow.flow')),
                ('lesson_time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_times', to='timetable.timelist')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_tables', to='Rooms.room')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_tables', to='Subjects.subjects')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_tables', to='Teachers.teacher')),
            ],
        ),
    ]
